### ISSUE TITLE
dual booting blackarch with windows 10

### ISSUE THREAD

**Issue by WebJ0K3R** [BlackArch/blackarch-installer#22]
I have windows preinstalled in legacy mode , I installed blackarch using it's installer in another drive i created but blackarch isn't booting , windows is booting automatically. how should i make it dualbootable , plz provide exact steps(I'm newbie to arch) .

**Comment by bounteous17** [comment]
Give me more info: (fdisk -l, parted -l)

First of all connect to Internet 'systemctl start dhcpcd' or Wifi 'wifi-menu', in that case do a 'ifconfig wlp5s0 down' before, for example. (use your wireless interface name)

If you have also installed BlackArch in Legacy, try to boot an Arch or BlackArch iso from usb, mount all your partitions of the separated Blackarch hdd, for example: (it's used on rescue procces)
mkdir -p /mnt/black/
mount /dev/sda2 /mnt/black/
mount /dev/sda1 /mnt/black/boot

After it chroot with 'arch-chroot', like:
arch-chroot /mnt/black

And then install 'pacman -Syy os-prober' to detect windows, after it, still inside the chroot environment and run a grub-mkconfig -o /boot/grub/grub.cfg, then reboot and unplug the Usb. On the bios choose the first boot option the drive where BlackArch is installed because now it's where grub is installed and configured to select linux or windows.

**Comment by PedroSFreitas** [comment]
Just to add up to what bounteous said, our current installer does not support dual booting out of the bat. Your best choice is following Arch Linux installation and later add BlackArch repository.

Thanks.

@noptrix close.
