### ISSUE TITLE
A need for saved progess

### ISSUE THREAD

**Issue by c99zealot** [BlackArch/blackarch-installer#48]
during the install process if anything fails for any reason the script stops running completely and falls back to the a shell prompt, if the user has already completed most of the steps they are now required to either attempt the rest of the install manually or, if they do not require the skills for that, re-run the script from the beginning, this is pretty tedious and caused me to give up and install vanilla arch with the blackarch repos

**Comment by Edu4rdSHL** [comment]
@mrsmith0x00 what do you think of using a file that save the actual step being executed, check if it finished successfully and then read the file if the installation fails?, for example:

- If the `setup_connection()` step was success but `disk_partition()` failed, then we should have a file with `disk_partition()`, if the user run the installer again the file is read and the installer continues in`disk_partition()` step instead of the beginning. Basically, when a step is success it's deleted  and the next step is written to the file, if it fails we can continue with the step that match the file.

**Comment by Edu4rdSHL** [comment]
I have introduced error handling which prevents the installer leaving because typos or common user-errors and leaving explicitly only for unrecoverable errors. That should avoid the need for this.
