### ISSUE TITLE
passwd command missing, endless loop

### ISSUE THREAD

**Issue by Silur** [BlackArch/blackarch-installer#74]
Previously seen in the main repo: https://github.com/BlackArch/blackarch/issues/3210

This is still happening with the **latest** 2021.09.01 netinstall ISO on the website

**Comment by yawns** [comment]
I mentioned a workaround in another issue about this - https://github.com/BlackArch/blackarch-installer/issues/73

The installer is shipping with an outdated keyring package that contains an invalid PGP signature, so absolutely nothing gets installed (we only see the "passwd missing" part because it loops there). To fix, make sure you're connected to the network, update the keyring, then update the installer (last part probably isn't necessary but doesn't hurt).

`pacman -Syy archlinux-keyring` and `pacman -Syy blackarch-installer`

After those two succeed, you can run the installer. I suppose this will be needed until a new release ships with the updated package.
